# Generated by Django 4.1 on 2022-09-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='notification_email',
            field=models.CharField(default='a@gmail.com', max_length=100),
        ),
    ]
